/**
 * Server-side helpers for reading the auth-session cookie set by the
 * SIWS verify endpoint.
 *
 * The cookie is `vizzor.auth=<rawToken>`; the *raw* token never lives
 * anywhere except in the HttpOnly cookie. The DB row stores
 * `SHA-256(rawToken)` so a DB snapshot leak cannot be replayed against
 * the live site as an authentication credential. This is the v0.2.x
 * security pass (Layer B1) — see `docs/security/threat-model.md`.
 *
 * The hashing is intentionally a single SHA-256 pass, NOT bcrypt /
 * argon2: these are high-entropy random 256-bit tokens generated by
 * `generateAuthToken()`, not user-chosen passwords, so a fast hash is
 * appropriate. The cost of an attacker who has the DB hash is the
 * full 2^256 search space; key stretching adds no value.
 */

import { cookies } from 'next/headers';
import { createHash } from 'node:crypto';
import { getAuthSession, deleteAuthSession } from './db';
import { findActiveSubscriptionByWallet, type SubscriptionRow } from './db';

/**
 * The canonical (legacy) auth-cookie name. New deployments under HTTPS
 * also accept and prefer `__Host-vizzor.auth` per RFC 6265bis §4.1.3.2:
 * the prefix is browser-enforced as Path=/ + Secure + no Domain, so a
 * subdomain cannot forge or shadow the cookie. Local dev (NODE_ENV !==
 * 'production') still uses the plain name because `__Host-` requires
 * Secure, which a localhost HTTP origin cannot satisfy.
 */
export const AUTH_COOKIE = 'vizzor.auth';
export const AUTH_COOKIE_HOST = '__Host-vizzor.auth';

/** Pick the right cookie name to emit on Set-Cookie based on environment. */
export function authCookieName(): string {
  return process.env.NODE_ENV === 'production' ? AUTH_COOKIE_HOST : AUTH_COOKIE;
}

export interface ActiveSession {
  wallet: string;
  expiresAt: number;
}

/**
 * One-way derivation of the DB lookup key from the raw cookie token.
 * Output is 64 hex chars (SHA-256). The migration in `db.ts` deletes
 * any legacy auth_sessions rows whose token isn't 64 hex chars on
 * boot, forcing the affected users to re-sign in once.
 */
export function hashAuthToken(raw: string): string {
  return createHash('sha256').update(raw).digest('hex');
}

export async function getActiveSession(): Promise<ActiveSession | null> {
  const jar = await cookies();
  // Prefer the hardened `__Host-` cookie if present, fall back to the
  // legacy name. Browsers that received the new cookie pre-rotation
  // continue to send the legacy one until it expires; we honour both
  // until the legacy 24h TTL has rolled over for every active session.
  const raw = jar.get(AUTH_COOKIE_HOST)?.value ?? jar.get(AUTH_COOKIE)?.value;
  if (!raw) return null;
  const hashed = hashAuthToken(raw);
  const row = getAuthSession(hashed);
  if (!row) return null;
  if (row.expires_at <= Date.now()) {
    deleteAuthSession(hashed);
    return null;
  }
  return { wallet: row.wallet_address, expiresAt: row.expires_at };
}

export async function getSubscriptionForActiveSession(): Promise<SubscriptionRow | null> {
  const sess = await getActiveSession();
  if (!sess) return null;
  return findActiveSubscriptionByWallet(sess.wallet, Date.now());
}
