#!/usr/bin/env bash
#
# configure-env.sh — fill /opt/7aylabs/.env and .env.staging with safe
# defaults so the stack can be brought up immediately.
#
# What this script generates automatically (cryptographically random):
#   - VIZZOR_BOT_SHARED_SECRET    (per env, 32 bytes base64url)
#   - VIZZOR_RATE_LIMIT_SALT      (per env, 32 bytes base64url)
#
# What this script sets to safe defaults:
#   PROD (/opt/7aylabs/.env)
#     - NODE_ENV=production
#     - NEXT_PUBLIC_PAYMENT_NETWORK=mainnet
#     - NEXT_PUBLIC_ACCEPT_SOLANA_PAYMENTS=false   <- kill switch ON until
#                                                     operator provides
#                                                     mainnet RPC + treasury
#     - NEXT_PUBLIC_TG_BOT_USERNAME=vizzorai_bot
#     - SOLANA_RPC_URL_MAINNET=__OPERATOR_REQUIRED__
#     - VIZZOR_SOLANA_TREASURY_MAINNET=__OPERATOR_REQUIRED__
#
#   STAGING (/opt/7aylabs/.env.staging)
#     - NODE_ENV=production            (same as prod — runtime mode is unchanged)
#     - NEXT_PUBLIC_PAYMENT_NETWORK=devnet
#     - NEXT_PUBLIC_ACCEPT_SOLANA_PAYMENTS=true   <- payments fully on
#     - NEXT_PUBLIC_TG_BOT_USERNAME=vizzorai_test_bot
#     - SOLANA_RPC_URL_DEVNET=https://api.devnet.solana.com
#     - NEXT_PUBLIC_SOLANA_RPC_URL_DEVNET=https://api.devnet.solana.com
#     - VIZZOR_SOLANA_TREASURY_DEVNET=__OPERATOR_REQUIRED__
#     - VIZZOR_EXTRA_ORIGINS=https://test.vizzor.ai
#
# Backs up the existing files to /opt/7aylabs/.env.bak.<ts> before
# overwriting, so a misconfigured prior state isn't lost.
#
# Usage:
#   sudo bash /srv/site-vizzor/scripts/configure-env.sh
#
# After this you still need to manually fill the three values still
# marked __OPERATOR_REQUIRED__ before bringing the prod container up.
# Staging needs only the devnet treasury; the rest is ready.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: this script must be run as root (use sudo)" >&2
  exit 2
fi

STACK_DIR="/opt/7aylabs"
TS="$(date +%Y%m%d-%H%M%S)"

if [[ ! -d "$STACK_DIR" ]]; then
  echo "ERROR: $STACK_DIR does not exist. Run bootstrap-stack.sh first." >&2
  exit 1
fi

gen_secret() {
  # 32 random bytes -> base64url -> strip padding/non-url chars -> 43 chars.
  openssl rand -base64 48 | tr -d '/+=\n' | head -c 43
}

write_prod() {
  local f="$STACK_DIR/.env"
  if [[ -f "$f" ]]; then cp -a "$f" "$f.bak.$TS"; fi

  local bot_secret rate_salt
  bot_secret="$(gen_secret)"
  rate_salt="$(gen_secret)"

  cat > "$f" <<ENV
# /opt/7aylabs/.env — PRODUCTION (vizzor.ai, mainnet)
# Generated by configure-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Two values are still marked __OPERATOR_REQUIRED__ and must be filled
# in before flipping NEXT_PUBLIC_ACCEPT_SOLANA_PAYMENTS=true:
#   - SOLANA_RPC_URL_MAINNET           (private RPC provider URL)
#   - VIZZOR_SOLANA_TREASURY_MAINNET   (mainnet wallet pubkey)
# Until both are real values, the kill switch below keeps the watcher
# from booting and the /pay routes serve "infrastructure pending".

# ── Runtime mode ────────────────────────────────────────────────
NODE_ENV=production

# ── Upstream engine ─────────────────────────────────────────────
VIZZOR_API_URL=https://api.vizzor.ai
NEXT_PUBLIC_VIZZOR_API_URL=https://api.vizzor.ai

# ── Persistent DB inside the named volume ───────────────────────
VIZZOR_SITE_DB=/app/.vizzor/site.db

# ── Solana — mainnet (kill switch ON until RPC+treasury wired) ──
NEXT_PUBLIC_ACCEPT_SOLANA_PAYMENTS=false
NEXT_PUBLIC_PAYMENT_NETWORK=mainnet
NEXT_PUBLIC_PAYMENT_RATE_LOCK_SECONDS=300
SOLANA_RPC_URL_MAINNET=__OPERATOR_REQUIRED__
NEXT_PUBLIC_SOLANA_RPC_URL_MAINNET=__OPERATOR_REQUIRED__
VIZZOR_SOLANA_TREASURY_MAINNET=__OPERATOR_REQUIRED__

# ── Bot transport ───────────────────────────────────────────────
VIZZOR_BOT_SHARED_SECRET=$bot_secret
NEXT_PUBLIC_TG_BOT_USERNAME=vizzorai_bot

# ── Rate-limit + origin defense ─────────────────────────────────
VIZZOR_RATE_LIMIT_SALT=$rate_salt

# ── Free-tier predict quota ─────────────────────────────────────
NEXT_PUBLIC_FREE_PREDICTIONS=3
ENV
  chmod 600 "$f"
  echo "  wrote $f"
}

write_staging() {
  local f="$STACK_DIR/.env.staging"
  if [[ -f "$f" ]]; then cp -a "$f" "$f.bak.$TS"; fi

  local bot_secret rate_salt
  bot_secret="$(gen_secret)"
  rate_salt="$(gen_secret)"

  cat > "$f" <<ENV
# /opt/7aylabs/.env.staging — STAGING (test.vizzor.ai, devnet)
# Generated by configure-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Only one value is __OPERATOR_REQUIRED__:
#   - VIZZOR_SOLANA_TREASURY_DEVNET   (devnet wallet pubkey; fund with
#                                      \`solana airdrop 2 <pubkey> --url devnet\`)
# Everything else is ready. Payments are ON; the engine accepts devnet
# transfers end-to-end.

# ── Runtime mode (same as prod — security middleware behaves identically) ─
NODE_ENV=production

# ── Upstream engine (single-tenant; staging shares prod engine) ──
VIZZOR_API_URL=https://api.vizzor.ai
NEXT_PUBLIC_VIZZOR_API_URL=https://api.vizzor.ai

# ── Persistent DB inside the STAGING named volume ────────────────
VIZZOR_SITE_DB=/app/.vizzor/site.db

# ── Solana — devnet, public RPC, payments ON ────────────────────
NEXT_PUBLIC_ACCEPT_SOLANA_PAYMENTS=true
NEXT_PUBLIC_PAYMENT_NETWORK=devnet
NEXT_PUBLIC_PAYMENT_RATE_LOCK_SECONDS=300
SOLANA_RPC_URL_DEVNET=https://api.devnet.solana.com
NEXT_PUBLIC_SOLANA_RPC_URL_DEVNET=https://api.devnet.solana.com
VIZZOR_SOLANA_TREASURY_DEVNET=__OPERATOR_REQUIRED__

# ── Bot transport (separate secret from prod) ───────────────────
VIZZOR_BOT_SHARED_SECRET=$bot_secret
NEXT_PUBLIC_TG_BOT_USERNAME=vizzorai_test_bot

# ── Rate-limit + origin defense ─────────────────────────────────
VIZZOR_RATE_LIMIT_SALT=$rate_salt
VIZZOR_EXTRA_ORIGINS=https://test.vizzor.ai

# ── Free-tier predict quota ─────────────────────────────────────
NEXT_PUBLIC_FREE_PREDICTIONS=3
ENV
  chmod 600 "$f"
  echo "  wrote $f"
}

echo "▶ Configuring /opt/7aylabs/.env and .env.staging with safe defaults"
write_prod
write_staging

echo ""
echo "── Remaining __OPERATOR_REQUIRED__ values ──"
grep -H __OPERATOR_REQUIRED__ "$STACK_DIR/.env" "$STACK_DIR/.env.staging" || true

echo ""
echo "── Next steps ──"
echo ""
echo "STAGING is ready to boot once you set the devnet treasury:"
echo "  1. Generate a fresh Solana devnet keypair (on your laptop):"
echo "       solana-keygen new --no-bip39-passphrase -o ~/vizzor-staging-treasury.json"
echo "       solana-keygen pubkey ~/vizzor-staging-treasury.json"
echo "  2. Edit /opt/7aylabs/.env.staging and replace __OPERATOR_REQUIRED__"
echo "     for VIZZOR_SOLANA_TREASURY_DEVNET with that pubkey."
echo "  3. Fund it with the devnet faucet:"
echo "       solana airdrop 2 <pubkey> --url devnet"
echo ""
echo "PROD will boot in 'payments off' mode until you wire mainnet:"
echo "  1. Choose a private mainnet RPC provider (Helius / Triton / QuickNode)."
echo "  2. Edit /opt/7aylabs/.env and replace __OPERATOR_REQUIRED__ for"
echo "     SOLANA_RPC_URL_MAINNET, NEXT_PUBLIC_SOLANA_RPC_URL_MAINNET, and"
echo "     VIZZOR_SOLANA_TREASURY_MAINNET."
echo "  3. Once verified, flip NEXT_PUBLIC_ACCEPT_SOLANA_PAYMENTS=true."
echo ""
echo "Then pull + up -d:"
echo "  echo <ghcr-pat> | docker login ghcr.io -u <github-user> --password-stdin"
echo "  cd /opt/7aylabs"
echo "  docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d site-vizzor-staging"
echo "  docker compose -f docker-compose.yml -f docker-compose.prod.yml    up -d site-vizzor"
echo ""
echo "DONE."
